
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cleverbuilder.bookservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.annotations.EndpointProperties;
import org.apache.cxf.annotations.EndpointProperty;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-14T16:40:06.280+02:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "BookService",
                      portName = "BookServiceSOAP",
                      targetNamespace = "http://www.cleverbuilder.com/BookService/",
                      wsdlLocation = "file:/home/sysfrog/IdeaProjects/WSDLTest/src/main/resources/rules.wsdl",
                      endpointInterface = "com.cleverbuilder.bookservice.BookService")
@EndpointProperties(value = { 
        @EndpointProperty(key = "ws-security.callback-handler", value = "com.cleverbuilder.bookservice.ServerPasswordCallback"), 
        @EndpointProperty(key = "ws-security.validate.token", value = "true") 
    } 
) 
public class BookServiceSOAPImpl implements BookService {

    private static final Logger LOG = Logger.getLogger(BookServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cleverbuilder.bookservice.BookService#getBook(java.lang.String id, java.lang.String title, java.lang.String author)*
     */
    public void getBook(javax.xml.ws.Holder<java.lang.String> id, javax.xml.ws.Holder<java.lang.String> title, javax.xml.ws.Holder<java.lang.String> author) {
        LOG.info("Executing operation getBook");
        System.out.println(id.value);
        try {
            java.lang.String titleValue = "";
            title.value = titleValue;
            java.lang.String authorValue = "";
            author.value = authorValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cleverbuilder.bookservice.BookService#addBook(java.lang.String title, java.lang.String author)*
     */
    public java.lang.String addBook(java.lang.String title, java.lang.String author) {
        LOG.info("Executing operation addBook");
        System.out.println(title);
        System.out.println(author);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cleverbuilder.bookservice.BookService#getAllBooks()*
     */
    public java.util.List<com.cleverbuilder.bookservice.GetAllBooksResponse.Book> getAllBooks() {
        LOG.info("Executing operation getAllBooks");
        try {
            java.util.List<com.cleverbuilder.bookservice.GetAllBooksResponse.Book> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
